# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/semantic-abstraction-blenderproc',
                'doc_host': 'https://flupppi.github.io',
                'git_url': 'https://github.com/flupppi/semantic-abstraction-blenderproc',
                'lib_path': 'semantic_abstraction_blenderproc'},
  'syms': { 'semantic_abstraction_blenderproc.core': { 'semantic_abstraction_blenderproc.core.foo': ( 'core.html#foo',
                                                                                                      'semantic_abstraction_blenderproc/core.py')}}}
